/**
 * Format a BrandVoiceProfile as Markdown (with optional ANSI color for TTY).
 */

const isTTY = typeof process !== "undefined" && process.stdout?.isTTY;

// ANSI color codes (only used in TTY mode)
const c = isTTY
  ? {
      reset: "\x1b[0m",
      bold: "\x1b[1m",
      dim: "\x1b[2m",
      red: "\x1b[31m",
      green: "\x1b[32m",
      yellow: "\x1b[33m",
      blue: "\x1b[34m",
      magenta: "\x1b[35m",
      cyan: "\x1b[36m",
      white: "\x1b[37m",
      gray: "\x1b[90m",
      bgRed: "\x1b[41m",
      bgGreen: "\x1b[42m",
      bgYellow: "\x1b[43m",
    }
  : {
      reset: "", bold: "", dim: "", red: "", green: "", yellow: "",
      blue: "", magenta: "", cyan: "", white: "", gray: "",
      bgRed: "", bgGreen: "", bgYellow: "",
    };

export function formatMarkdown(profile) {
  const { brand, url, pagesAnalyzed, pageBreakdown, summary, tone, vocabulary, structure, personality, guidelines, aiPrompt } = profile;

  const toneTable = tone.dimensions
    .map((d) => {
      const left = d.left || d.name.split(" ↔ ")[0];
      const right = d.right || d.name.split(" ↔ ")[1];
      const bar = renderBar(d.score);
      return `| ${left.padEnd(14)} ${bar} ${right.padEnd(14)} | ${colorScore(d.score)} |`;
    })
    .join("\n");

  const archetypeDisplay = personality.archetypes.map((a) => `${c.bold}${a}${c.reset}`).join(", ");
  const traitDisplay = personality.traits.map((t) => `${c.cyan}${t}${c.reset}`).join(", ");

  const sigPhrases = vocabulary.signaturePhrases?.length
    ? `\n**Signature Phrases:** ${vocabulary.signaturePhrases.map((p) => `"${p.phrase}" (×${p.count})`).join(", ")}`
    : "";

  const pageList = pageBreakdown
    ? `\n**Pages crawled:**\n${pageBreakdown.map((p) => `  ${zoneEmoji(p.zone)} ${p.title || p.url} ${c.dim}(${p.zone})${c.reset}`).join("\n")}`
    : "";

  return `${c.bold}# 🎙️ Brand Voice Profile: ${brand}${c.reset}

${c.dim}> ${summary}${c.reset}

**Source:** ${url}
**Pages analyzed:** ${pagesAnalyzed}${pageList}

---

## Tone Spectrum

| Dimension | Score |
|-----------|-------|
${toneTable}

## Personality

**Archetypes:** ${archetypeDisplay}
**Traits:** ${traitDisplay}

## Vocabulary DNA

- **Total words analyzed:** ${vocabulary.totalWords.toLocaleString()}
- **Unique words:** ${vocabulary.uniqueWords.toLocaleString()}
- **Vocabulary richness:** ${vocabulary.vocabularyRichness}
- **Average word length:** ${vocabulary.averageWordLength} chars

**Power Words:** ${vocabulary.powerWords.slice(0, 15).map((w) => `\`${w.word}\``).join(", ")}
${vocabulary.jargon.length ? `\n**Industry Jargon:** ${vocabulary.jargon.join(", ")}` : ""}${sigPhrases}

## Writing Structure

- **Average sentence length:** ${structure.averageSentenceLength} words
- **Reading level:** ${structure.readingLevel.label} (Grade ${structure.readingLevel.grade})
- **Questions:** ${Math.round(structure.questionRatio * 100)}% of sentences
- **Exclamations:** ${Math.round(structure.exclamationRatio * 100)}% of sentences
- **Imperatives (CTAs):** ${Math.round(structure.imperativeRatio * 100)}% of sentences

## Brand Voice Guidelines

### ✅ Do
${guidelines.dos.map((d) => `- ${c.green}${d}${c.reset}`).join("\n")}

### ❌ Don't
${guidelines.donts.map((d) => `- ${c.red}${d}${c.reset}`).join("\n")}

## 🤖 AI Prompt (Copy & Paste)

Use this prompt to make any AI write in ${brand}'s voice:

\`\`\`
${aiPrompt}
\`\`\`

---

*Generated by [brand-voice](https://github.com/SlashImagine/brand-voice) v2.0*
`;
}

/**
 * Format as JSON string.
 */
export function formatJSON(profile) {
  return JSON.stringify(profile, null, 2);
}

function renderBar(score) {
  const filled = Math.round(score);
  const empty = 10 - filled;
  if (isTTY) {
    // Color the bar based on score direction
    const barColor = score >= 7 ? c.green : score >= 5 ? c.yellow : score <= 3 ? c.red : c.white;
    return `${barColor}${"█".repeat(filled)}${c.dim}${"░".repeat(empty)}${c.reset}`;
  }
  return "◼".repeat(filled) + "◻".repeat(empty);
}

function colorScore(score) {
  const label = `${score}/10`;
  if (!isTTY) return label;
  if (score >= 7) return `${c.green}${label}${c.reset}`;
  if (score <= 3) return `${c.red}${label}${c.reset}`;
  return `${c.yellow}${label}${c.reset}`;
}

function zoneEmoji(zone) {
  switch (zone) {
    case "voice": return "🎯";
    case "homepage": return "🏠";
    case "noise": return "🔇";
    default: return "📄";
  }
}
