/**
 * Format a BrandVoiceProfile as Markdown.
 */
export function formatMarkdown(profile) {
  const { brand, url, pagesAnalyzed, summary, tone, vocabulary, structure, personality, guidelines, aiPrompt } = profile;

  const toneTable = tone.dimensions
    .map((d) => {
      const [low, high] = d.name.split(" ↔ ");
      const bar = renderBar(d.score);
      return `| ${low.padEnd(12)} ${bar} ${high.padEnd(12)} | ${d.score}/10 |`;
    })
    .join("\n");

  return `# 🎙️ Brand Voice Profile: ${brand}

> ${summary}

**Source:** ${url}
**Pages analyzed:** ${pagesAnalyzed}

---

## Tone Spectrum

| Dimension | Score |
|-----------|-------|
${toneTable}

## Personality

**Archetypes:** ${personality.archetypes.join(", ")}
**Traits:** ${personality.traits.join(", ")}

## Vocabulary DNA

- **Total words analyzed:** ${vocabulary.totalWords.toLocaleString()}
- **Unique words:** ${vocabulary.uniqueWords.toLocaleString()}
- **Vocabulary richness:** ${vocabulary.vocabularyRichness}
- **Average word length:** ${vocabulary.averageWordLength} chars

**Power Words:** ${vocabulary.powerWords.slice(0, 15).map((w) => `\`${w.word}\``).join(", ")}
${vocabulary.jargon.length ? `\n**Industry Jargon:** ${vocabulary.jargon.join(", ")}` : ""}

## Writing Structure

- **Average sentence length:** ${structure.averageSentenceLength} words
- **Reading level:** ${structure.readingLevel.label} (Grade ${structure.readingLevel.grade})
- **Questions:** ${Math.round(structure.questionRatio * 100)}% of sentences
- **Exclamations:** ${Math.round(structure.exclamationRatio * 100)}% of sentences
- **Imperatives (CTAs):** ${Math.round(structure.imperativeRatio * 100)}% of sentences

## Brand Voice Guidelines

### ✅ Do
${guidelines.dos.map((d) => `- ${d}`).join("\n")}

### ❌ Don't
${guidelines.donts.map((d) => `- ${d}`).join("\n")}

## 🤖 AI Prompt (Copy & Paste)

Use this prompt to make any AI write in ${brand}'s voice:

\`\`\`
${aiPrompt}
\`\`\`

---

*Generated by [brand-voice](https://github.com/SlashImagine/brand-voice)*
`;
}

/**
 * Format as JSON string.
 */
export function formatJSON(profile) {
  return JSON.stringify(profile, null, 2);
}

function renderBar(score) {
  const filled = Math.round(score);
  const empty = 10 - filled;
  return "◼".repeat(filled) + "◻".repeat(empty);
}
